/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LCD.h>
#include <FanController.h>
#include <SW1_aliases.h>
#include <SW1.h>
#include <SW2_aliases.h>
#include <SW2.h>
#include <tach_1_aliases.h>
#include <tach_1.h>
#include <pwm_1_aliases.h>
#include <pwm_1.h>
#include <EOC_SR.h>
#include <Clock_1.h>
#include <Clock_2.h>
#include <ADC_DelSig_1.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <ADC_DelSig_1_AMux.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_IRQ.h>
#include <ADC_DelSig_1_theACLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

